services:
  db:
    container_name: db
    image: postgres:16.4
    restart: always
    environment:
      - POSTGRES_USER=${PG_USER}
      - POSTGRES_PASSWORD=${PG_PASSWORD}
      - POSTGRES_DB=${PG_DB}
    ports:
      - "9090:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - bot_network

  tg-bot-back:
    container_name: tg-bot-back
    image: tg-bot-back
    build:
      context: ./
      dockerfile: tg-bot-back/Dockerfile
    environment:
      - JAVA_OPTS=-Xmx512M
      - TG_BOT_NAME=${TG_BOT_NAME}
      - TG_BOT_TOKEN=${TG_BOT_TOKEN}
    restart: on-failure
    networks:
      - bot_network

volumes:
  postgres_data:

networks:
  bot_network:
    driver: bridge