server:
  port: 9091

spring:
  application:
    name: crud-microservice
  config:
    import: optional:file:.env[.properties]
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${PG_DB}
    username: ${PG_USER}
    password: ${PG_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: create-drop # none
    show-sql: false
  liquibase:
    enabled: false # true
    change-log: classpath:/db/changelog/changelog.xml